name: PHP Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '1 * * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: run script
        run: php bind_blocked_update.php
      - name: update files
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            domains.txt
            named.conf.blocked
          commit-msg: Autoupdate
          github-token: ${{ secrets.GITHUB_TOKEN }}
